server:
  port: 8881


spring:
  profiles:
    active: development
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
        show_sql: true
        format_sql: true
  liquibase:
    enabled: true

logging:
  level:
    root: INFO